verif: verify_signature_versionC.c
	gcc verify_signature_versionC.c -o verify_signature_versionC -lssl -lcrypto
sign: digital_signature_versionC.c
	gcc digital_signature_versionC.c -o digital_signature -lssl -lcrypto
